server:
  port: 1111

spring:
  application:
    name: admin-server
  output:
    ansi:
      enabled: always

  cloud:
    discovery:
      enabled: true  # Enables Eureka discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

webclient:
  connect-timeout: 5000  # 5 seconds
  read-timeout: 5000     # 5 seconds
  retry:
    max-attempts: 3      # Retry 3 times
    backoff: 2000        # 2 seconds backoff
